### ISSUE TITLE
[core] Develop Database Connection Page

### ISSUE THREAD

**Issue by prodbyola** [prodbyola/basable#16]
We're developing the database connection page according to our design guideline:
<img width="1280" alt="Screenshot 2024-07-12 at 8 21 12 AM" src="https://github.com/user-attachments/assets/fa09cfad-46ff-4a22-bb38-0b6ba99b98c2">

We're building with Nuxt and Nuxt UI.

Please [Join us on slack](https://join.slack.com/t/basableteam/shared_invite/zt-2mlo086ub-~TKzgUVHNapV9h8aFb_qMg) to get access to our figma UI design.

**Comment by DeathKnight813** [comment]
Hi @prodbyola.

I will complete this issue#16.
Please wait for my pull request.
