### ISSUE TITLE
[landing] Create "Benefit" section

### ISSUE THREAD

**Issue by prodbyola** [prodbyola/basable#19]
If you're looking for a challenge, please create the "Benefit" section of our landing page. This is a React Project. To gain access to the original figma file, please join our slack Team: https://join.slack.com/t/basable/shared_invite/zt-2mlo086ub-~TKzgUVHNapV9h8aFb_qMg

<img width="708" alt="Screenshot 2024-07-16 at 8 57 52 AM" src="https://github.com/user-attachments/assets/6ecb79e7-72e4-49e5-b4cc-a255ef3d14c2">

## How To
* Fork the project and clone your version.
* Go to landing directory `cd basable/landing`.
* Install dependencies using your favorite package manager: `npm install`.
* Develop the "Benefit" component and add it to `App.js`.
* Push your changes and create a PR.

We'll review and merge your updates. Thanks.

**Comment by ShedrachJonah11** [comment]
I’ll like to work on this.

**Comment by prodbyola** [comment]
Thank you Shedrach, do you have access to the figma file? Or have you joined us on Slack?

**Comment by ShedrachJonah11** [comment]
I don’t have access to the figma,
I have joined the slack already

**Comment by Chioma-Okeke** [comment]
Oh shoot. Taken already😅. So fast

**Comment by prodbyola** [comment]
> Oh shoot. Taken already😅. So fast

@Chioma-Okeke No worries! There several other components we want to build. We'll be posting more issues in our slack channel.

**Comment by prodbyola** [comment]
> Oh shoot. Taken already😅. So fast

Here's another quick issue, if you're interested: https://github.com/prodbyola/basable/issues/20

**Comment by kobby18-50** [comment]
I thought I was assigned to this .....I am even working on it

**Comment by ShedrachJonah11** [comment]
> I thought I was assigned to this .....I am even working on it

was assigned to me i guess lol

**Comment by kobby18-50** [comment]
I have made some progress 
You can pull mine and add yours

**Comment by ShedrachJonah11** [comment]
> I have made some progress You can pull mine and add yours

okay, which of the PR's

**Comment by kobby18-50** [comment]
Someone has already worked on it

**Comment by ShedrachJonah11** [comment]
> Someone has already worked on it

Just saw that.
seems i'll just stash what i have on local

**Comment by kobby18-50** [comment]
Okay sure

**Comment by prodbyola** [comment]
> I thought I was assigned to this .....I am even working on it

Hey @kobby18-50 
 I'm very sorry to hear that. We usually merge the first PR that fixes an issue. This is because many developers take up an issue and abandon it, even after we dedicate the issue to them.
In order to make up for your efforts, I'll create another issue and assign it for you to fix. Apologies once again.

**Comment by kobby18-50** [comment]
Sure thing sir
Kindly assign me to the next available issue
