### ISSUE TITLE
[landing] Set App 'max-width' to 1280px

### ISSUE THREAD

**Issue by prodbyola** [prodbyola/basable#20]
We want to restrict the width of the app component to 1280px max in order to provide width constraints on very large screens. 

## Requirement
On extra-large screens, the website must be horizontally positioned at the center of the screen and must not be wider than 1280px;

## How To Contribute
* Fork the project and clone your version.
* Go to landing directory `cd basable/landing`.
* Install dependencies using your favorite package manager: `npm install`.
* Edit `App.css` to fulfill requirements.
* Push your changes and create a PR.

**Comment by TRIPLE-ADE** [comment]
Would love to work on this

**Comment by prodbyola** [comment]
> Would love to work on this

Looking forward to your PR.

**Comment by Joverth** [comment]
It is no problem for me.
Perfect!

**Comment by DeathKnight813** [comment]
I'm Robert, and will fix this problem right now.

**Comment by DeathKnight813** [comment]
Please add me as collaborator in the repository.
I can't push the code.
