### ISSUE TITLE
Add SEO Metadata

### ISSUE THREAD

**Issue by prodbyola** [prodbyola/basable#26]
We need to add SEO metadata to the landing page using the following information:

*Title:* Basable Open-Source Software
*Description:* Basable is an open-source software designed to provide comprehensive data management, data visualization, and business insights
*Image:* https://drive.google.com/file/d/17ItWGZVnNHIEI79j0cZeIdVr4iZ6Jq1W/view?usp=sharing

We prefer that the SEO standard conforms to [Open Graph Protocol](https://ogp.me/).

**Comment by TRIPLE-ADE** [comment]
I would like to work on this

**Comment by prodbyola** [comment]
> I would like to work on this

Thank you! We take the discussion to our slack channel.

**Comment by Patrick-Chukwu** [comment]
I just sent a PR for this
