### ISSUE TITLE
[landing] Create a Side Drawer for Navigation on Mobile Device

### ISSUE THREAD

**Issue by prodbyola** [prodbyola/basable#27]
Our page navigation is currently toggled on a Popover (please see video below). We would prefer to have it on nice-looking Side Drawer. Please see attached image for a sample Side Drawer. However, our drawer should be aligned to the right hand side.

https://github.com/user-attachments/assets/0ae46478-cb19-400c-9f77-1978a3fb6afe

![drawer](https://github.com/user-attachments/assets/bd559405-4994-4d0e-860c-f9459bd98b28)

**Comment by Patrick-Chukwu** [comment]
I will work on this
