### ISSUE TITLE
[landing] Add Invitation Form section

### ISSUE THREAD

**Issue by prodbyola** [prodbyola/basable#28]
We would like to Invitation Form section to our landing page. Please see image below to take a glimpse at what the form would look like. [Join us on Slack](https://join.slack.com/t/basable/shared_invite/zt-2mlo086ub-~TKzgUVHNapV9h8aFb_qMg) to gain access to our figma file.

## How To
* Fork the project and clone your version.
* Go to landing directory `cd basable/landing`.
* Install dependencies using your favorite package manager: `npm install`.
* Develop the "Invitation" component and add it to `App.js`.
* Push your changes and create a PR.

<img width="514" alt="Screenshot 2024-07-20 at 12 07 45 AM" src="https://github.com/user-attachments/assets/e5286725-026a-4683-9a85-845e0dc67052">

**Comment by ShedrachJonah11** [comment]
Working on this..
