### ISSUE TITLE
Authentication Page

### ISSUE THREAD

**Issue by prodbyola** [prodbyola/basable#40]
Our design team has delivered the authentication page for Basable (see screenshots below). We need a volunteer to develop this page for us. Please [join us on Discord](https://discord.gg/XWuPKKS5gr) for access to Figma template.

#### What You Need to Do
* The main **authentication page** should in `web/src/pages/AuthPage.tsx`.
* The form (a reactive component) should be in `web/src/components/forms/AuthForm.tsx`.
* Add the `AuthPage` to our routes in `web/src/App.tsx` as the root of the url "/".

If you have any question or need clarity, please [join us on Discord](https://discord.gg/XWuPKKS5gr).

![image](https://github.com/user-attachments/assets/5f2004d7-acb8-40d0-bc88-af43e73089f3)

**Comment by Netbash** [comment]
okay i"ll  volunter
